// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isjbijahkuivexwxhefa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzamJpamFoa3VpdmV4d3hoZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTg5MzcsImV4cCI6MjA2OTQ3NDkzN30.oPtsrjZdYRnU6BdD3hgX0fQLQq1RiyTM2IGAa2pw8hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});